const brands = [
 {id:"burmatex",num:"01",name:"Burmatex",type:"Wykładziny dywanowe w płytkach i panelach",tag:"50 × 50 cm · 25 × 100 cm",desc:"Brytyjskie wykładziny komercyjne do intensywnie użytkowanych wnętrz. Modułowy format pozwala tworzyć indywidualne układy, ułatwia serwis i wymianę pojedynczych elementów.",uses:["Hotele i apartamenty","Biura i coworking","Akustyka i komfort","Montaż w całej Polsce"],lines:["Surface Story","Arctic","Rocklines","Threads","Tivoli","Balance Collection"],url:"https://www.burmatex.com.pl/",samples:[{n:"Vibe — aranżacja biurowa",i:"https://assets.remland.co.uk/images/products/630x630/7735/vibe-carpet-tiles-113328.jpg?v=2026-2",u:"https://www.burmatex.com.pl/produkty/"},{n:"Arctic — Hail Stone",i:"https://cdn11.bigcommerce.com/s-3a3ee/images/stencil/1280x1280/products/27785/71613/Hail_Stone__95371.1681993310.png?c=2",u:"https://www.burmatex.com.pl/plytki-dywanowe/artic-panele-dywanowe/"},{n:"Threads — Mix",i:"https://fenstoncarter.co.uk/cdn/shop/files/threads-plain-single-tile-mix_2048x2048.jpg?v=1741660986",u:"https://www.burmatex.com.pl/produkty/"}]},
 {id:"tarkett",num:"02",name:"Tarkett",type:"Naturalne podłogi drewniane",tag:"Design · natura · ponadczasowość",desc:"Szlachetna podłoga drewniana do reprezentacyjnych wnętrz hotelowych, gabinetów i apartamentów. Starannie dobrane wzory podkreślają architekturę i prestiż przestrzeni.",uses:["Pokoje i apartamenty","Gabinety i sale zarządu","Naturalne wykończenie","Doradztwo materiałowe"],lines:["Pure","Shade","Prestige","Segno","Noble","Professional"],url:"https://www.tarkett.pl/",samples:[{n:"Professional Oak Nature",i:"https://media.tarkett-image.com/large-high/IN_HP_Wood-ProfessionalOakNatureTreS-7825012_7870077_7870078_8721007_005.jpg",u:"https://mieszkaniowe.tarkett.pl/pl_PL/kategoria-cee_R01012-podlogi-drewniane"},{n:"Pure Oak Nature",i:"https://media.tarkett-image.com/large/IN_7879003_7879004_004.jpg",u:"https://mieszkaniowe.tarkett.pl/pl_PL/kategoria-cee_R01012-podlogi-drewniane"},{n:"Prestige Boardwalk Oak",i:"https://www.doorsandfloors.co.uk/images/source/tarkett-oak/prestige-room-_.jpg",u:"https://mieszkaniowe.tarkett.pl/pl_PL/kategoria-cee_R01012-podlogi-drewniane"}]},
 {id:"forbo",num:"03",name:"Forbo",type:"Podłogi LVT do obiektów komercyjnych",tag:"Wysoka rotacja · łatwy serwis · nowoczesny design",desc:"Nowoczesne panele i płytki LVT łączą realistyczny wygląd drewna lub kamienia z parametrami potrzebnymi w przestrzeniach komercyjnych. Praktyczny wybór do szybkich realizacji i modernizacji.",uses:["Lobby i komunikacja","Restauracje i usługi","Biura i retail","Łatwa pielęgnacja"],lines:["Allura Wood","Allura Material","Allura Flex","Allura Click","Allura Puzzle","Allura Decibel"],url:"https://www.forbo.com/",samples:[{n:"Allura Light Giant Oak",i:"https://forbo.azureedge.net/productimages/room/243545_60288DR5.webp",u:"https://www.forbo.com/flooring/en-gl/products/luxury-vinyl-tiles/allura-dryback-0-7-dr7/allura-dryback-0-7-wood/bhs9s7?dnr=60288DR7"},{n:"Allura Natural Concrete",i:"https://images.belago.de/sq1000/files/d/6/d66ac4000af376145b8da9f4a139878d.jpg",u:"https://www.forbo.com/flooring/en-gl/products/luxury-vinyl-tiles/allura-dryback-0-7-dr7/allura-dryback-0-7-material/ba7kcm?dnr=63634DR7"},{n:"Allura Decibel Oak",i:"https://contractflooring.com/cdn/shop/files/244391_5224AD8_1.webp?v=1695387338&width=540",u:"https://www.forbo.com/flooring/en-gl/products/luxury-vinyl-tiles/allura-decibel/pgacev"}]}
];

export default function Home(){return <main>
 <header><a className="officialLogo" href="#top"><img src="/hotelia-brand-logo.png" alt="Hotelia — Premium Finish Solutions"/></a><nav><a href="#oferta">Oferta</a><a href="#obsluga">Obsługa</a><a href="#kontakt">Kontakt</a></nav><div className="headerRight"><span className="alkMini">ALK</span><a className="outline" href="mailto:ALK@hotelia.com?subject=Zapytanie%20HOTELIA">Zapytaj o ofertę</a></div></header>
 <section className="hero" id="top"><div className="grid"/><div className="heroCopy"><img className="heroLogo" src="/hotelia-brand-logo.png" alt="Logo Hotelia"/><p className="eyebrow">WYSELEKCJONOWANE ROZWIĄZANIA DLA INWESTYCJI</p><h1>Podłogi, które budują<br/><em>charakter wnętrza.</em></h1><p className="lead">Trzy renomowane marki. Jedna odpowiedzialna obsługa — od doboru kolekcji i wyceny, przez logistykę, aż po profesjonalny montaż w całej Polsce.</p><div className="actions"><a className="btn" href="#oferta">Poznaj ofertę</a><a className="phone" href="tel:+48730231528">+48 730 231 528</a></div></div><div className="samples"><img className="heritageLogo" src="/hotelia-brand-logo.png" alt="Oficjalne złote logo Hotelia"/><i className="carpet"/><i className="wood"/><i className="lvt"/><span/></div><div className="categories">HOTELE <i/> BIURA <i/> APARTAMENTY <i/> OBIEKTY KOMERCYJNE</div></section>
 <section className="intro" id="oferta"><div><p className="eyebrow">01 — NASZA OFERTA</p><h2>Tylko trzy marki.<br/>Każda wybrana świadomie.</h2></div><p>Nie jesteśmy przypadkowym katalogiem. Koncentrujemy się na trzech komplementarnych systemach podłogowych, które pozwalają kompleksowo projektować przestrzenie hotelowe i biurowe.</p></section>
 <section className="brands">{brands.map(b=><article className={`brand ${b.id}`} key={b.id}><div className="visual"><sup>{b.num}</sup><strong>{b.name}</strong><small>HOTELIA SELECTION</small></div><div className="copy"><p className="eyebrow">{b.type}</p><h3>{b.name}</h3><p className="tag">{b.tag}</p><p className="desc">{b.desc}</p><div className="uses">{b.uses.map(x=><span key={x}>✓ {x}</span>)}</div><p className="label">WYBRANE LINIE PRODUKTOWE</p><div className="chips">{b.lines.map(x=><span key={x}>{x}</span>)}</div><a className="more" href={b.url} target="_blank" rel="noreferrer">Poznaj ofertę producenta ↗</a></div><div className="productGallery">{b.samples.map(s=><a className="productSample" href={s.u} target="_blank" rel="noreferrer" key={s.n}><img src={s.i} alt={`${b.name} — ${s.n}`}/><span><b>{s.n}</b><small>Zobacz produkt ↗</small></span></a>)}</div></article>)}</section>
 <section className="service" id="obsluga"><p className="eyebrow">02 — KOMPLEKSOWA OBSŁUGA</p><h2>Od koncepcji<br/>do gotowej podłogi.</h2><div className="steps">{[["01","Rozpoznanie potrzeb","Analizujemy obiekt, funkcję pomieszczeń, estetykę, budżet i harmonogram."],["02","Dobór rozwiązania","Dopasowujemy kolekcję, format, kolorystykę i parametry techniczne."],["03","Wycena i logistyka","Przygotowujemy przejrzystą ofertę i koordynujemy dostawy na inwestycję."],["04","Montaż i serwis","Zapewniamy instalację i obsługę posprzedażową w całej Polsce."]].map(s=><div className="step" key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></section>
 <section className="promise"><p>HOTELIA / STANDARD PREMIUM</p><blockquote>„Tworzymy przestrzenie, które budują prestiż, zapewniają komfort i pozostają piękne na lata.”</blockquote><div>JAKOŚĆ ◆ DESIGN ◆ TRWAŁOŚĆ</div></section>
 <section className="contact" id="kontakt"><div><p className="eyebrow">03 — KONTAKT</p><h2>Porozmawiajmy<br/>o Twojej inwestycji.</h2><p>Prześlij rzut, zestawienie powierzchni lub zapytanie. Dobiorę rozwiązanie i przygotuję ofertę dla hotelu, biura lub obiektu komercyjnego.</p><a className="downloadLink" href="/Adam-Leo-Kosyl-Hotelia.vcf" download>↓ Pobierz kontakt do telefonu</a></div><div className="businessCard"><div className="bcTop"><span className="alkMonogram"><b>A</b><b>L</b><b>K</b></span><img className="cardHoteliaLogo" src="/hotelia-brand-logo.png" alt="Hotelia"/></div><div className="bcLine"/><p>PRZEDSTAWICIEL HANDLOWY</p><h3>Adam Leo Kosyl</h3><a href="tel:+48730231528">+48 730 231 528</a><a className="primaryMail" href="mailto:ALK@hotelia.com">ALK@hotelia.com</a><a href="mailto:adamleokosyl@gmail.com">adamleokosyl@gmail.com</a><div className="bcActions"><a className="btn" href="mailto:ALK@hotelia.com?subject=Zapytanie%20ofertowe%20HOTELIA">Napisz wiadomość</a><a className="qrHint" href="/Adam-Leo-Kosyl-Hotelia.vcf" download>VCARD ↓</a></div></div></section>
 <footer><img className="footerLogo" src="/hotelia-brand-logo.png" alt="Hotelia"/><p>Premium Finish Solutions</p><span className="footerAlk">ALK</span><p>© 2026 Hotelia · Adam Leo Kosyl</p></footer>
 </main>}
